name: BEELINE
channels:
  - defaults
dependencies:
  - python=3.7.1
  - r=3.5.0
  - pip
  - rpy2==2.9.1
  - matplotlib==3.0.2
  - pandas==0.23.4
  - networkx==2.2
  - seaborn==0.9.0
  - tqdm==4.28.1
  - numpy==1.15.4
  - scikit-learn==0.21.2
  - PyYAML==5.4
  - pip:
    - mygene==3.2.2