#!/bin/bash

### PBS Job Batch Options
### Note: No commands may be executed until after the #PBS lines
### Account information
#PBS -W group_list=cu_10145 -A cu_10145
### Job name (comment out the next line to get the name of the script used as the job name)
#PBS -N infody
### Output files (comment out the next 2 lines to get the job name used instead)
#PBS -e infody.err
#PBS -o infody.log
### Only send mail when job is aborted or terminates abnormally
#PBS -m n
### Number of nodes
#PBS -l nodes=1:ppn=1
### Memory
#PBS -l mem=8gb
### Requesting time - format is <days>:<hours>:<minutes>:<seconds> (here, 12 hours), CHECK THIS CAREFULLY, MUCH SLOWER THAN LOCAL WORKSTATION
### 
#PBS -l walltime=04:00:00
### Add current shell environment to job (comment out if not needed)
###PBS -V
### Forward X11 connection (comment out if not needed)
###PBS -X

### Script below ###
conda activate
cd $PBS_O_WORKDIR
