name: CNNC
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.12
  - tensorflow==2.18.0
  - keras
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - h5py
  - time
  - gcc
  - gxx
  - gxx_linux-64
  - tensorflow-estimator