name: CNNC
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - tensorflow=2.1.0
  - keras
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - h5py=2.10
  - time
  - gcc
  - gxx
  - gxx_linux-64
  - theano
  - tensorflow-estimator=2.1.0