name: CNNC
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - tensorflow
  - keras
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - h5py=3.14.0
  - time
  - gcc
  - gxx
  - gxx_linux-64
  - theano
  - tensorflow-estimator