name: CNNC
channels:
  - anaconda
  - conda-forge
  - bioconda
  - nvidia
  - defaults
dependencies:
  - python==3.12
  - keras
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - h5py
  - time
  - gcc
  - gxx
  - gxx_linux-64
  - tensorflow-estimator
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio