name: CNNC
channels:
  - anaconda
  - conda-forge
  - bioconda
  - nvidia
  - defaults
dependencies:
  - python==3.12
  - pytorch-gpu==2.7.1
  - torchvision
  - torchaudio
  - keras
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - h5py
  - time
  - gcc
  - gxx
  - gxx_linux-64
  - tensorflow-estimator
  - pip
  - pip:
    - torch